"""create_managers_table

Revision ID: 72d431ed2df7
Revises: 1ec267e6607e
Create Date: 2026-05-13 14:56:09.684386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72d431ed2df7'
down_revision: Union[str, None] = '1ec267e6607e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('middle_name', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('avatar_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_managers_id'), 'managers', ['id'], unique=False)
    op.create_index(op.f('ix_managers_last_name'), 'managers', ['last_name'], unique=False)
    op.create_index(op.f('ix_managers_username'), 'managers', ['username'], unique=True)
    op.create_index(op.f('ix_group_vacations_id'), 'group_vacations', ['id'], unique=False)
    op.create_index(op.f('ix_payment_receipts_id'), 'payment_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_student_notes_id'), 'student_notes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_notes_id'), table_name='student_notes')
    op.drop_index(op.f('ix_payment_receipts_id'), table_name='payment_receipts')
    op.drop_index(op.f('ix_group_vacations_id'), table_name='group_vacations')
    op.drop_index(op.f('ix_managers_username'), table_name='managers')
    op.drop_index(op.f('ix_managers_last_name'), table_name='managers')
    op.drop_index(op.f('ix_managers_id'), table_name='managers')
    op.drop_table('managers')
    # ### end Alembic commands ###
